### ISSUE TITLE
Enhancement Request:  Support for Roku Global Search

### ISSUE THREAD

**Issue by robross0606** [ljunkie/rarflix#245]
I'm not sure if this is even possible, but it would be absolutely awesome if RARflix exposed my media library to Roku's built-in global search.  This might not even be available in Roku's API, but figured I would make the request and see.

**Comment by ljunkie** [comment]
I'd love to add this, as I bet many others would too, but Roku has not exposed anything for developers.

**Comment by robross0606** [comment]
Hopefully in the future.  Seems pretty short-sighted of Roku but one can always hope it's in the roadmap.  Thanks for responding.
