### ISSUE TITLE
Roku ultra LT issues

### ISSUE THREAD

**Issue by klikevil** [ljunkie/rarflix#251]
I have two roku ultras one is like an xs edition (the only difference I can tell is between the remotes it has 2 shortcut buttons) on the one without the extra letters it is braking and saying rarflix is no longer available but works fine on the other one.

https://pastebin.com/gSsBtT1P

any thoughts or a patch or anything at all would be helpful really.  I wish so many nice projects for the roku/plex weren't abandoned.

**Comment by LiquidTeaJa** [comment]
@klikevil it's because of the recent roku operating system update. 
we need someone to re-write the rarflix app so that it works on the roku 11.5 operating system. 
 wondering if @ljunkie could sort this?

**Comment by ljunkie** [comment]
hey all! this channel was written in SDK1 and Roku has finally removed the ability run SDK1 apps in OS 11.5. https://blog.roku.com/developer/roku-os-11-5
